config/routes.rb
Rails.application.routes.draw do

  get '/games', to: 'pages#gameshub'
  get '/games/hangman', to: 'games#hangman'
  get '/games/pokeclimb', to: 'games#pokeclimb'
  get '/games/ekans', to: 'games#pokesnake'
  get '/games/show', to: 'pages#show'
  get '/home', to: 'pages#index'
  get '/pokemart', to: 'pages#pokemart'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'

    authenticated do
      root to: 'pages#index'
    end

    unauthenticated  do
      root to: 'devise/sessions#new'
    end
  end

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  after_create_commit { BroadcastMessageJob.perform_later self }
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cards, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def hangman
  end

  def snake
  end

  def pokeclimb
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @messages = Message.all
    @users = User.all
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit( :username,
                                  :email,
                                  :password,
                                  :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit( :username, 
                                  :email,
                                  :password,
                                  :password_confirmation,
                                  :current_password)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def show
    @users = User.all
    @messages = Message.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @cards = Card.all
  end

  private
  def card_params
    params.require(:card).permit(:set, :number, :user_id, :imageLink)
  end
end

app/helpers/application_helper.rb
require 'navigation_helper.rb'

module ApplicationHelper
  include NavigationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper

  def collapsible_links_partial_path
    if user_signed_in?
      'layouts/navigation/collapsible_elements/signed_in_links'
    else
      'layouts/navigation/collapsible_elements/non_signed_in_links'
    end
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/hangman.html.erb
<div id="youWin" class="modalWin">
    <div id="dexContent">
      <%= image_tag("hangman/pokedex-bg.gif", id: "dex") %>
      <%= image_tag("hangman/oak-win.png", id: "profOak") %>
      <p class="pokeText"> Great Catches!<br><br><a href="#" id="resetLink" data-turbolinks="false">Play Again?</a></p>
      <div id="dexEntry">
      </div>
      <a id="prevEntry"class="prevEntry">&#10094;</a>
      <a id="nextEntry"class="nextEntry">&#10095;</a>
      <div class="bgWhite"></div>
    </div>
  </div>

  <div id="youLose" class="modalLose">
    <div class="contentLose">
      <%= image_tag("hangman/gary-lose.png", id: "rivalGary") %>
      <%= image_tag("hangman/kanto-badges.png", id: "badges") %>
      <%= image_tag("hangman/textbox.png", id: "textBox") %>
      <img id="pokeImg3" src="" alt="">
      <div class="loseDiv">
        <p id="loseText"></p>
        <a href="#" id="resetLink2" data-turbolinks="false">Try Again?</a>
      </div>
    </div>
  </div>

  <div class="wrapper">
    <div class="header">
      <h1 id="title">Name that Pokemon!</h1>
      <h3 id="generation">Gen I</h3>
    </div>
    <div class="display">
      <div class="wordOutput">
        <p><strong>Pokemon:</strong></p>
        <h1 id="pokemonName"></h1>
      </div>

      <div class="guessed">
        <p><strong>Used Letters:</strong></p><p id="usedLetters"></p>
      </div>

      <div class="display-bottom-row">
        <div class="lives">
          <p><strong>Lives:</strong></p>
          <%= image_tag("hangman/pokeball-life.png", id: "life1") %>
          <%= image_tag("hangman/pokeball-life.png", id: "life2") %>
          <%= image_tag("hangman/pokeball-life.png", id: "life3") %>
          <%= image_tag("hangman/pokeball-life.png", id: "life4") %>
          <%= image_tag("hangman/pokeball-life.png", id: "life5") %>
          <%= image_tag("hangman/pokeball-life.png", id: "life6") %>
        </div>

        <div class="score">
          <p><strong>Score:</strong></p><p id="score">0</p>
        </div>
      </div>

      <div class="display-right-column">
        <div class="timerSection">
          <p><strong>Timer:</strong></p><p id="timer"></p>
        </div>

        <div class="hintSection">
          <!-- <button id="hintBttn" title="Need a hint?">Show Hint</button> -->
          <div id="hintBox">
            <p class"typeTitle"><strong>Type:</strong></p>
            <div id="type"></div>
            <div id="type2"></div>
          </div>
        </div>
      </div>
    </div>

    <div class="keyboard">
      <div class="row1">
        <button class="letters" value="A">A</button>
        <button class="letters" value="B">B</button>
        <button class="letters" value="C">C</button>
        <button class="letters" value="D">D</button>
        <button class="letters" value="E">E</button>
        <button class="letters" value="F">F</button>
        <button class="letters" value="G">G</button>
        <button class="letters" value="H">H</button>
        <button class="letters" value="I">I</button>
        <button class="letters" value="J">J</button>
        <button class="letters" value="K">K</button>
        <button class="letters" value="L">L</button>
        <button class="letters" value="M">M</button>
      </div>

      <div class="row2">
        <button class="letters" value="N">N</button>
        <button class="letters" value="O">O</button>
        <button class="letters" value="P">P</button>
        <button class="letters" value="Q">Q</button>
        <button class="letters" value="R">R</button>
        <button class="letters" value="S">S</button>
        <button class="letters" value="T">T</button>
        <button class="letters" value="U">U</button>
        <button class="letters" value="V">V</button>
        <button class="letters" value="W">W</button>
        <button class="letters" value="X">X</button>
        <button class="letters" value="Y">Y</button>
        <button class="letters" value="Z">Z</button>
      </div>

      <div class="resetKey">
        <button id="resetBttn" data-turbolinks="false">RESET</button>
      </div>

      <%= javascript_include_tag 'games/hangman.js' %>
    </div>
  </div>

app/views/games/pokeclimb.html.erb
<%= javascript_include_tag 'phaser.min.js' %>
<%= javascript_include_tag 'games/pokeclimb.js' %>

app/views/games/pokesnake.html.erb
<%= javascript_include_tag 'phaser.min.js' %>
<%= javascript_include_tag 'games/pokesnake.js' %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="row">

      <!-- Elements visible all the time -->
      <div class="col-sm-7">
        <%= render 'layouts/navigation/header' %>
      </div><!-- col-sm-7 -->

      <!-- Elements collapses on smaller devices -->
      <div class="col-sm-5">
        <%= render 'layouts/navigation/collapsible_elements' %>
      </div><!-- col-sm-5 -->

    </div><!-- row -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokeCenter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('poke-favicon.png'), :rel => 'icon', :type =>  'image/png' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/navigation/_collapsible_elements.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse navbar-right" id="navbar-collapsible-content">
  <ul class="nav navbar-nav ">
    <%= render collapsible_links_partial_path %>
  </ul>
</div><!-- navbar-collapse -->

app/views/layouts/navigation/_header.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapsible-content" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%= image_tag("pokecenter.png", class:'navbar-brand') %>
  <a href="/home" class='navbar-brand' data-turbolinks="false">PokéCenter</a>
</div>

app/views/layouts/navigation/collapsible_elements/_non_signed_in_links.html.erb
<li ><%= link_to 'Login', login_path %></li>
<li ><%= link_to 'Signup', signup_path %></li>

app/views/layouts/navigation/collapsible_elements/_signed_in_links.html.erb
<li class="dropdown nav-link pc-menu">
  <a href="/games" data-turbolinks="false">Games Hub</a>
</li>

<li class="dropdown nav-link pc-menu">
  <a href="/pokemart" data-turbolinks="false">PokéMart</a>
</li>

<li class="dropdown nav-link pc-menu">
  <a href="https://pokemonshowdown.com/" target="_blank">Battle</a>
</li>

<li class="dropdown nav-link pc-menu">
  <a id="user-settings" class="dropdown-toggle" data-toggle="dropdown" href="#">
    <span id="user-name"><%= current_user.username %></span>
    <span class="caret"></span>
  </a>

  <ul class="dropdown-menu" role="menu">
    <li><a href='/users/<%= current_user.id %>'>Profile</a></li>
    <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
    <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
  </ul>
</li>

<li class="mobile-menu">
  <a href="/games" id="games-link" data-turbolinks="false">Games Hub</a>
</li>
<li class="mobile-menu">
  <a href="/pokemart" id="store-link" data-turbolinks="false">PokéMart</a>
</li>
<li class="mobile-menu">
  <a href="https://pokemonshowdown.com/" target="_blank">Battle</a>
</li>
<li class="mobile-menu">
  <%= link_to 'Edit Profile', edit_user_registration_path %>
</li>
<li class="mobile-menu">
  <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
</li>

app/views/messages/_message.html.erb
<div class="message">
  <% profile = message.user.icon %>
  <%= image_tag(profile, id: "text-profile") %>
  <a href="" class="message_username"><%= message.user.username %>:</a>
  <span class="message_content">
    <%= message.content %>
  </span>
</div>
<div class="message_timestamp">
  <%= message.created_at %>
</div>

app/views/pages/gameshub.html.erb
<div id="gameshub-bg">
  <div class="carousel">
  	<figure>
      <%= image_tag("SS_pokeclimb", class: "game-image") %>
      <%= image_tag("SS_hangman", class: "game-image") %>
      <%= image_tag("SS_pokesnake", class: "game-image") %>
  	</figure>
    <div id="gamesInfo">
      <p id="description" class="text-center">Tap/Click to Jump! Climb Bulbasaur's vines and avoid the other Pokémon!</p>
    </div>
  	<div id="gamesNav">
  		<button class="navBttn prev btn btn-default">Prev</button>
      <a href="/games/pokeclimb" id="game-link" class="btn btn-default" data-turbolinks="false">Play</a>
  		<button class="navBttn next btn btn-default">Next</button>
  	</div>
  </div>
</div>

app/views/pages/index.html.erb
<div id="chatroom" class="container">
  <div class="row">
    <div id="side-menu"  class="col-sm-3">
      <div id="trainer-list">
        <% @users.each do |u| %>
          <div class="trainer-option">
            <% profile = u.icon %>
            <%=image_tag(profile, id: "chat-profile") %>
            <a href="#" class="chat-link"><%= u.username %></a>
          </div>
        <% end %>
      </div>
      <div class="theme-bttns">
        <div class="vertical-align">
          <button type="button" id="theme1"></button>
          <button type="button" id="theme2"></button>
          <button type="button" id="theme3"></button>
          <button type="button" id="theme4"></button>
        </div>
      </div>
    </div><!-- side-menu -->

    <div class="col-sm-9">
      <div id="messages">
        <%= render @messages %>
      </div>
      <div class="input-box">
        <textarea type="text" id="message_input"></textarea>
        <a href="#" id="sendButton" onclick="sendMessage()">Send</a>
      </div>
    </div><!-- main-content -->

  </div><!-- row -->
</div><!-- container -->

<%= javascript_include_tag 'chatThemes.js' %>

app/views/pages/pokemart.html.erb
<div class="container">
  <div class="row">
    <div id="storeWorker" class="col-sm-4">
      <%= image_tag("pokemart-logo.png", id: "pokemart-logo") %>
      <%= image_tag("pokemart-workers.png", id: "pokemart-workers") %>
      <%= image_tag("textbox.png", id: "text-box") %>
      <div id="store-text-placement">
        <p id="store-text">Welcome to the PokéMart!</p>
      </div>
      <div class="store-bttns">
          <button type="button" id="buy-icons" class="shop-bttn">
            <%= image_tag("20g.png") %><span>Portraits [20g]</span>
          </button>
          <button type="button" id="buy-cards" class="shop-bttn">
            <%= image_tag("50g.png") %><span>Pokémon Cards [50g]</span>
          </button>
      </div>
    </div>

    <div id="storeStock" class="col-sm-8">
      <div id="icon-selection">
        <div class="original-icons">
          <h1>Original Gen I Sprites</h1>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/original/sprite-ash.png") %></button>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/original/sprite-brock.png") %></button>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/original/sprite-misty.png") %></button>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/original/sprite-rival.png") %></button>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/original/sprite-rocket.png") %></button>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/original/sprite-giovanni.png") %></button>
        </div>

        <div class="poke-icons">
          <h1>Pokemon Portraits</h1>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/pokemon/portrait-growlithe.png") %></button>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/pokemon/portrait-squirtle.png") %></button>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/pokemon/portrait-pidgeotto.png") %></button>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/pokemon/portrait-machop.png") %></button>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/pokemon/portrait-kakuna.png") %></button>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/pokemon/portrait-staryu.png") %></button>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/pokemon/portrait-snorlax.png") %></button>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/pokemon/portrait-nidoking.png") %></button>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/pokemon/portrait-lapras.png") %></button>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/pokemon/portrait-mew.png") %></button>
        </div>

        <div class="character-icons">
          <h1>Misc Character Portraits</h1>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/characters/icon-may.png") %></button>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/characters/icon-brendan.png") %></button>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/characters/icon-archie.png") %></button>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/characters/icon-lass.png") %></button>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/characters/icon-picnickerF.png") %></button>
          <button type="button" class="portrait-bttn"><%= image_tag("portraits/characters/icon-hiker.png") %></button>
        </div>
      </div>


      <div id="card-selection">
        <div class="base-set">
          <button type="button" class="cardSet-bttn"><%= image_tag("cards/cards-base.png") %></button>
          <div class="set-description">
            <h4><strong>Base Set</strong></h4>
            <p>1/09/1999</p>
          </div>
        </div>


        <div class="jungle-set">
          <button type="button" class="cardSet-bttn"><%= image_tag("cards/cards-jungle.png") %></button>
          <div class="set-description">
            <h4><strong>Jungle Set</strong></h4>
            <p>6/16/1999</p>
          </div>
        </div>

        <div class="promo-set">
          <button type="button" class="cardSet-bttn"><%= image_tag("cards/cards-promo.png") %></button>
          <div class="set-description">
            <h4><strong>Jungle Set</strong></h4>
            <p>6/16/1999</p>
          </div>
        </div>

        <div class="fossil-set">
          <button type="button" class="cardSet-bttn"><%= image_tag("cards/cards-fossil.png") %></button>
          <div class="set-description">
            <h4><strong>Wizards Black Star Promo Set</strong></h4>
            <p>7/01/1999</p>
          </div>
        </div>

        <div class="base-set-2">
          <button type="button" class="cardSet-bttn"><%= image_tag("cards/cards-base-2.png") %></button>
          <div class="set-description">
            <h4><strong>Base Set 2</strong></h4>
            <p>2/24/2000</p>
          </div>
        </div>

        <div class="rocket-set">
          <button type="button" class="cardSet-bttn"><%= image_tag("cards/cards-rocket.png") %></button>
          <div class="set-description">
            <h4><strong>Team Rocket Set</strong></h4>
            <p>4/24/2000</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag 'pokemart.js' %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div id="profile-top" class="col-sm-9">
      <div id="profile-image-div">
        <% profile = current_user.icon %>
        <%=image_tag(profile, id: "profile-image") %>
      </div>
      <div id="profile-info">
        <h3><strong><%=current_user.username %></strong></h3>
        <p><%=current_user.email %></p>
        <% if current_user.showdownId != "" %>

        <h3><strong>Showdown ID</strong></h3>
        <p><%=current_user.showdownId %></p>
        <% end %>
      </div>

      <div id="pofile-coins" class="profile-scores">
        <h3><strong>Coins</strong></h3>
        <p><%=current_user.coins %></p>
      </div>
      <div id="pofile-hangman" class="profile-scores">
        <h3><strong>Hangman</strong></h3>
        <p><%=current_user.hangman_score %></p>
      </div>
      <div id="pofile-climb" class="profile-scores">
        <h3><strong>PokéClimb</strong></h3>
        <p><%=current_user.climb_score %></p>
      </div>
      <div id="pofile-snake" class="profile-scores">
        <h3><strong>Snake</strong></h3>
        <p><%=current_user.snake_score %></p>
      </div>
    </div>

    <div id="profile-bottom" class="col-sm-9">
      <div class="">
        <h3><%=current_user.username%>'s Pokémon Cards</h3>
      </div>
      <div id="card-section">
        <% @cards.each do |c| %>
          <% if c.user_id == current_user.id %>
            <img src="<%=c.imageLink%>" alt="">
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>